## I Objectives

* Recognize when a reaction occurs.
* Record initial observation of solutions including pH, color, odor, viscosity, etc.
* Learn how to describe and document the results of mixing solutions.
* Identify 5 unknown solutions based on the results of initial observations and reactivity.
* _Provide a brief proposal in your notebook addressing the basic experimental steps to meet these objectives. Once approved, work with your team of investigators to collect and analyze the data._

## II Procedure Development

In order to identify each of the 5 unknown solutions, develop a method to react each solution with each of the others for a total of 10 combinations. Document the result of each mixture, use the results to help identify each of the 5 solutions. After identification, write an equation for the reactions that occur. NOTE THAT NOT ALL COMBINATIONS WILL RESULT IN A CHEMICAL REACTION.

_"For your reference, sample data tables are provided in section IV: DATA COLLECTION & CALCULATIONS_

_You will be provided one of the following sets of chemicals in bottles, each labeled with an unknown letter:_